export enum NotificationType {
  ADVANCED_ASSESSMENT_SCORE_READY = 'advanced_assessment_score_ready',
  ADVANCED_RETAKE_AVAILABLE = 'advanced_retake_available',
  OFFER_RECEIVED = 'offer_received',
  OFFER_ACCEPTED = 'offer_accepted',
  OFFER_DECLINED = 'offer_declined',
  OFFER_WITHDRAWN = 'offer_withdrawn',
  OFFER_EXPIRED = 'offer_expired',
  ASSESSMENT_UNLOCKED = 'assessment_unlocked',
  ASSESSMENT_WINDOW_EXPIRING = 'assessment_window_expiring',
  ASSESSMENT_PASSED = 'assessment_passed',
  ASSESSMENT_FAILED = 'assessment_failed',
  CONTACT_REQUEST_RECEIVED = 'contact_request_received',
  ASSESSMENT_RECEIVED = 'assessment_received',
  JOB_READY_MATCHES_AVAILABLE = 'job_ready_matches_available',
}

export const NOTIFICATION_TYPE_VALUES = [
  NotificationType.ADVANCED_ASSESSMENT_SCORE_READY,
  NotificationType.ADVANCED_RETAKE_AVAILABLE,
  NotificationType.OFFER_RECEIVED,
  NotificationType.OFFER_ACCEPTED,
  NotificationType.OFFER_DECLINED,
  NotificationType.OFFER_WITHDRAWN,
  NotificationType.OFFER_EXPIRED,
  NotificationType.ASSESSMENT_UNLOCKED,
  NotificationType.ASSESSMENT_WINDOW_EXPIRING,
  NotificationType.ASSESSMENT_PASSED,
  NotificationType.ASSESSMENT_FAILED,
  NotificationType.CONTACT_REQUEST_RECEIVED,
  NotificationType.ASSESSMENT_RECEIVED,
  NotificationType.JOB_READY_MATCHES_AVAILABLE,
] as const;
