import { DataSource } from 'typeorm';
import { Seeder } from './seeder.interface';

export const AssessmentQuestionsSeeder: Seeder = {
  name: 'AssessmentQuestionsSeeder',

  async run(dataSource: DataSource): Promise<void> {
    const repo = dataSource.getRepository('assessment_questions');

    // Check if already seeded
    const existingCount = await repo.count({
      where: { assessment_type: 'personal' },
    });

    if (existingCount > 0) {
      console.log(
        '✅ Personal assessment questions already seeded, skipping...',
      );
      return;
    }

    // Define all 48 personal assessment questions
    const questions = [
      // Section 1: Professional Background (10 questions)
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text: 'What is your current or most recent job title?',
        section: 1,
        question_number: 1,
        is_required: true,
        min_char_count: 2,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'How many years of total professional experience do you have?',
        section: 1,
        question_number: 2,
        is_required: true,
        min_char_count: null,
        options: ['0–1 yr', '1–3 yrs', '3–5 yrs', '5–10 yrs', '10+ yrs'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text: 'Which industries or sectors have you worked in?',
        section: 1,
        question_number: 3,
        is_required: true,
        min_char_count: null,
        options: [
          'Fintech',
          'Healthcare',
          'E-commerce',
          'Government',
          'NGO',
          'Media & Entertainment',
          'Education',
          'Logistics',
          'Telecoms',
          'Oil & Gas',
          'Agriculture',
          'Other (free text)',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is the largest organisation you have worked for?',
        section: 1,
        question_number: 4,
        is_required: true,
        min_char_count: null,
        options: [
          'Solo / freelance',
          '2–10',
          '11–50',
          '51–200',
          '201–1,000',
          '1,000+',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text:
          'Have you worked at a startup, a large corporation, or both?',
        section: 1,
        question_number: 5,
        is_required: true,
        min_char_count: null,
        options: [
          'Startup (<50)',
          'Mid-size',
          'Large corporation',
          'Government',
          'Freelance',
          'Self-employed',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is your highest level of completed education?',
        section: 1,
        question_number: 6,
        is_required: true,
        min_char_count: null,
        options: [
          'Secondary',
          'Diploma',
          "Bachelor's",
          "Master's",
          'PhD',
          'Professional certification',
          'Self-taught',
          'Other',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'Are you currently a student or in active training?',
        section: 1,
        question_number: 7,
        is_required: true,
        min_char_count: null,
        options: ['No', 'Yes, part-time', 'Yes, full-time'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text: 'In which country are you currently based?',
        section: 1,
        question_number: 8,
        is_required: true,
        min_char_count: 2,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text: 'Which city or region are you based in?',
        section: 1,
        question_number: 9,
        is_required: true,
        min_char_count: 2,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'What is your primary spoken language for professional work?',
        section: 1,
        question_number: 10,
        is_required: true,
        min_char_count: null,
        options: [
          'English',
          'French',
          'Arabic',
          'Portuguese',
          'Swahili',
          'Other (free text)',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 2: Skills & Expertise (8 questions)
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'Which skill track are you applying to be assessed on?',
        section: 2,
        question_number: 11,
        is_required: true,
        min_char_count: null,
        options: [
          'Software Engineering',
          'Data & Analytics',
          'Product Management',
          'Design (UI/UX)',
          'Marketing',
          'Sales',
          'Customer Support',
          'Finance & Accounting',
          'HR & People Ops',
          'Content & Copywriting',
          'DevOps & Cloud',
          'Other',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is your specialization within your track?',
        section: 2,
        question_number: 12,
        is_required: true,
        min_char_count: null,
        options: ['Dynamic options per track selected in Q11'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'How would you honestly rate yourself in your primary skill?',
        section: 2,
        question_number: 13,
        is_required: true,
        min_char_count: null,
        options: ['Entry', 'Junior', 'Mid', 'Senior', 'Expert'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text: 'Which tools or platforms do you use regularly?',
        section: 2,
        question_number: 14,
        is_required: false,
        min_char_count: null,
        options: ['Dynamic options per track. Other opens free-text field.'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'How long have you been working with your primary tool or stack?',
        section: 2,
        question_number: 15,
        is_required: true,
        min_char_count: null,
        options: [
          'Less than 6 months',
          '6–12 months',
          '1–2 years',
          '3–5 years',
          '5+ years',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you ever trained, mentored, or taught others in your area?',
        section: 2,
        question_number: 16,
        is_required: true,
        min_char_count: null,
        options: ['Yes, formally', 'Yes, informally', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you contributed to or shipped a product, project, or deliverable independently?',
        section: 2,
        question_number: 17,
        is_required: true,
        min_char_count: null,
        options: ['Yes, multiple times', 'Yes, once', 'Not yet'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'optional_text',
        question_text:
          'Do you have any published work, portfolio, or public profile we can reference?',
        section: 2,
        question_number: 18,
        is_required: false,
        min_char_count: null,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 3: Leadership & Responsibility (6 questions)
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'Have you ever managed a direct team?',
        section: 3,
        question_number: 19,
        is_required: true,
        min_char_count: null,
        options: [
          'No',
          'Yes — 1 to 3 people',
          'Yes — 4 to 10 people',
          'Yes — 10+ people',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text: 'Have you held any leadership title?',
        section: 3,
        question_number: 20,
        is_required: true,
        min_char_count: null,
        options: [
          'Team lead',
          'Manager',
          'Senior manager',
          'Head of department',
          'Director',
          'VP or C-suite',
          'None of the above',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'Describe a situation where you had to make a difficult decision that affected others at work.',
        section: 3,
        question_number: 21,
        is_required: true,
        min_char_count: 80,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you ever led a project from start to finish without direct supervision?',
        section: 3,
        question_number: 22,
        is_required: true,
        min_char_count: null,
        options: ['Yes, multiple times', 'Yes, once', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you been responsible for hiring or building a team?',
        section: 3,
        question_number: 23,
        is_required: false,
        min_char_count: null,
        options: ['Yes', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you ever managed a budget or been accountable for financial outcomes?',
        section: 3,
        question_number: 24,
        is_required: false,
        min_char_count: null,
        options: ['Yes, regularly', 'Yes, once or twice', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 4: International & Remote Experience (6 questions)
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you ever worked with or for organisations outside your home country?',
        section: 4,
        question_number: 25,
        is_required: true,
        min_char_count: null,
        options: ['Yes, extensively', 'Yes, occasionally', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'Have you worked in a fully remote or distributed team?',
        section: 4,
        question_number: 26,
        is_required: true,
        min_char_count: null,
        options: ['Yes, 2+ years', 'Yes, less than 2 years', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'How many time zones have you actively collaborated across?',
        section: 4,
        question_number: 27,
        is_required: false,
        min_char_count: null,
        options: [
          'Same time zone only',
          '1–2 time zones',
          '3–5 time zones',
          '6+ time zones',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you worked directly with international clients or stakeholders?',
        section: 4,
        question_number: 28,
        is_required: true,
        min_char_count: null,
        options: ['Yes, regularly', 'Yes, occasionally', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text:
          'Are you open to roles that are fully remote, hybrid, or in-person?',
        section: 4,
        question_number: 29,
        is_required: true,
        min_char_count: null,
        options: [
          'Fully remote',
          'Hybrid',
          'In-person only',
          'Flexible',
          'Open to any',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Do you have reliable internet access and a functional home workspace?',
        section: 4,
        question_number: 30,
        is_required: true,
        min_char_count: null,
        options: ['Yes, fully set up', 'Yes, mostly', 'Working on it', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 5: Work Style & Soft Skills (6 questions)
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'How do you typically handle tight deadlines or sudden priority shifts?',
        section: 5,
        question_number: 31,
        is_required: true,
        min_char_count: 60,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'Describe your ideal working environment — team dynamics, pace, structure.',
        section: 5,
        question_number: 32,
        is_required: true,
        min_char_count: 60,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'How do you prefer to receive feedback?',
        section: 5,
        question_number: 33,
        is_required: true,
        min_char_count: null,
        options: [
          'Directly and bluntly',
          'Bluntly but with context',
          'Gently with examples',
          'No preference',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'optional_text',
        question_text:
          'Have you ever had a significant professional disagreement? Briefly describe how you handled it.',
        section: 5,
        question_number: 34,
        is_required: false,
        min_char_count: 60,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'How do you typically manage your workload when juggling multiple responsibilities?',
        section: 5,
        question_number: 35,
        is_required: true,
        min_char_count: 60,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'Describe a time you had to learn something new quickly in a professional context.',
        section: 5,
        question_number: 36,
        is_required: true,
        min_char_count: 60,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 6: Achievements & Evidence (5 questions)
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'What is the single professional achievement you are most proud of and why?',
        section: 6,
        question_number: 37,
        is_required: true,
        min_char_count: 100,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'optional_text',
        question_text:
          'Have you delivered work with a measurable business impact? Describe it briefly — include a number if possible.',
        section: 6,
        question_number: 38,
        is_required: false,
        min_char_count: null,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text:
          'Have you received any professional recognition, certifications, or promotions in the last 3 years?',
        section: 6,
        question_number: 39,
        is_required: true,
        min_char_count: null,
        options: ['Yes', 'No'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: true,
      },
      {
        assessment_type: 'personal',
        question_type: 'optional_text',
        question_text:
          'Do you have any links to work you have shipped or contributed to publicly?',
        section: 6,
        question_number: 40,
        is_required: false,
        min_char_count: null,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'optional_text',
        question_text:
          'Is there anything about your background or career path that you think is important context for employers?',
        section: 6,
        question_number: 41,
        is_required: false,
        min_char_count: null,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },

      // Section 7: Availability & Intent (7 questions)
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What best describes your current job-search status?',
        section: 7,
        question_number: 42,
        is_required: true,
        min_char_count: null,
        options: [
          'Actively looking',
          'Open to the right opportunity',
          'Just exploring',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is your current availability?',
        section: 7,
        question_number: 43,
        is_required: true,
        min_char_count: null,
        options: [
          'Immediately available',
          'On notice (<1 month)',
          'On notice (1–3 months)',
          'Currently employed, flexible',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'multi_pick',
        question_text: 'What type of engagement are you open to?',
        section: 7,
        question_number: 44,
        is_required: true,
        min_char_count: null,
        options: [
          'Full-time',
          'Part-time',
          'Contract',
          'Freelance',
          'Open to all',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text: 'What is your preferred work location?',
        section: 7,
        question_number: 45,
        is_required: true,
        min_char_count: 2,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is your salary or compensation expectation?',
        section: 7,
        question_number: 46,
        is_required: false,
        min_char_count: null,
        options: [
          'No preference',
          'Below market is fine for the right role',
          'Market rate',
          'Above market',
        ],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'single_pick',
        question_text: 'What is your preferred currency for compensation?',
        section: 7,
        question_number: 47,
        is_required: false,
        min_char_count: null,
        options: ['NGN', 'USD', 'GBP', 'KES', 'GHS', 'ZAR', 'EUR', 'Other'],
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
      {
        assessment_type: 'personal',
        question_type: 'required_text',
        question_text:
          'In your own words, what kind of next role or opportunity are you looking for?',
        section: 7,
        question_number: 48,
        is_required: true,
        min_char_count: 80,
        options: null,
        correct_answer: null,
        track: null,
        level: null,
        has_follow_up: false,
      },
    ];

    // Save all questions
    await repo.save(questions);

    console.log(
      'Successfully seeded 48 personal assessment questions across 7 sections',
    );
    console.log('   - Section 1 (Professional Background): 10 questions');
    console.log('   - Section 2 (Skills & Expertise): 8 questions');
    console.log('   - Section 3 (Leadership & Responsibility): 6 questions');
    console.log('   - Section 4 (International & Remote): 6 questions');
    console.log('   - Section 5 (Work Style & Soft Skills): 6 questions');
    console.log('   - Section 6 (Achievements & Evidence): 5 questions');
    console.log('   - Section 7 (Availability & Intent): 7 questions');
  },
};
